### ISSUE TITLE
很不错的效果。

### ISSUE THREAD

**Issue by bufffun** [DianQK/TransitionTreasury#1]
我有一个疑问，就是转场结束后，我怎么样可以在second vc里拿到那个keyview呢，看源代码里面是在toVC里面加上了原来fromVC的一个view content的copy。

**Comment by dianqk** [comment]
关于这个我也在考虑，我做这个库的目的主要是尽可能的通用、简洁，所以这样的情况并没有过多的考虑，但依然有办法获得 ps.有些 (keyViewCopy) 我写成了私有的，刚刚想了不大合适。 **1.0.2** 版本已解决问题。   

获取的方法有大概以下两种：    

> 项目整体结构参见 [介绍](https://github.com/DianQK/TransitionTreasury/wiki/介绍)  章节。

#### 使用`tr_transition`

push 的转场都是把`tr_transition`放在第二个 VC 中，我用这个保留的动画委托实例、动画实例，从这里可以获取需要的值，比如 **IBanTang** 中的`keyView`和`keyViewCopy`的获取方法：    

``` swift
override func viewDidAppear(animated: Bool) {
        super.viewDidAppear(animated)
        print((tr_transition?.transition as? IBanTangTransitionAnimation)?.keyView)
        print((tr_transition?.transition as? IBanTangTransitionAnimation)?.keyViewCopy)
    }
```

present 的转场的`tr_transition`也不难获取：    

``` swift
print((modalDelegate as? MainViewController)?.tr_transition)
```

> 注意：
> 该用法可能需要稍后的 **1.0.2** 版本或以上版本。
> 我之所以写在`viewDidAppear(_:)`中，是因为`viewDidLoad(_:)`是还没有进行转场，动画实例自然还没有哩~，So，请注意要在转场结束获取。
> 与`tr_transition`有交互逻辑的都属于高级使用，切记不要再去保留`tr_transition`，否则很可能出现循环引用，其次最好不要更改里面的值，否则会出现奇怪的现象哦，只要需要更多需要定制的参数，或者写属于某些特别的 VC 中，再考虑这些即可~换句话说，我们可以通过`tr_transition`获取任何数据，甚至还可以用来正向传值。（请谨慎使用）    

#### 使用 Tag

我在 StoryBoard 中给`logoImageView`，设置`tag`为 2000 。之后即可通过`view.viewWithTag(20000)`获取到该视图。

> 注意：
> 需要 **1.0.2** 版本或以上版本。      
> 
> PS:
> ~~今天中午一点前我会修改好，并更新~~~**1.0.2 已更新**感谢提醒 ^^ ，如果还有什么问题尽管提~ 一个好的项目需要的不是更多的 Star，还是 issue 和 pr 更重要~

**Comment by bufffun** [comment]
在应用场景中这个keyview如果是一个imageView,那么image很有可能会变，或者是有点击事件之类的，所以加上是很有必要的。效率真高，赞一个。
