### ISSUE TITLE
Generic parameter 'T' could not be inferred

### ISSUE THREAD

**Issue by danho322** [DianQK/TransitionTreasury#13]
I've installed TransitionTreasury to my Swift project using Carthage, and am getting the Generic parameter 'T' could not be inferred error when trying to use tr_pushViewController. The viewController being pushed conforms to NavgationTransitionable correctly but the project still does not compile.

Are there any special instructions to use the library with Swift and Carthage?

**Comment by dianqk** [comment]
HiHi~  @danho322   I'm not sure what happened ? Maybe you can show your code :)

**Comment by danho322** [comment]
After rerunning the Carthage update and closing/opening Xcode a few times, it worked. Issue with Xcode it looks like :). Thank you!

**Comment by dianqk** [comment]
:)

**Comment by AlexEdunov** [comment]
I got the same error. I tried to reinstall library through CocoaPods a few times then I tried to drag sources to my project. Sadly I still didn't solve the problem.

**Comment by dianqk** [comment]
Hi~ @AlexEdunov 

Try this:

```
rm -rf ~/Library/Developer/Xcode/DerivedData/
```

**Comment by AlexEdunov** [comment]
The error is gone after installing TransitionAnimation extensions. Maybe I made a mistake in animation method implementation.

**Comment by gali8** [comment]
Be careful, the problem could be in the method parameter when you call the tr_pushViewController function.
Like below, use the prefix **TRPushTransitionMethod**.

Don't forget to add import TransitionAnimation

`navigationController?.tr_pushViewController(vc, method: TRPushTransitionMethod.OMIN(keyView: self.view), statusBarStyle: TRStatusBarStyle.LightContent, completion: nil)`

**Comment by MattiaConfalonieri** [comment]
I got the same problem... any solution?
