### ISSUE TITLE
Generic parameter 'T' could not be inferred

### ISSUE THREAD

**Issue by MattiaConfalonieri** [DianQK/TransitionTreasury#14]
Code give me this error.

xcode 7.3

**Comment by gali8** [comment]
Ciao Mattia, guarda tra gli issue chiusi. Ho risposto lì come fare (o aggiunto import TransitionAnimation
)

**Comment by MattiaConfalonieri** [comment]
Grazie della risposta ma purtroppo con la tua soluzione mi restituisce lo stesso errore...

**Comment by gali8** [comment]
pod 'TransitionTreasury', '~> 3.0.3' #transitions TransitionTreasury
pod 'TransitionAnimation', '~> 3.0.3' #transitions TransitionTreasury

li hai importati entrambi?

**Comment by MattiaConfalonieri** [comment]
Yes

**Comment by gali8** [comment]
su che punto ti da il problema?

**Comment by MattiaConfalonieri** [comment]
su tr_pushViewController mi segnala  Generic parameter 'T' could not be inferred 

nel momento di fare il push del controller , ho aggiunto entrambi i pod e importato nel controller sia Treasury che Animation ma niente da fare...

**Comment by gali8** [comment]
me lo dava anche a me.
- Il secondo vc (quello che devi mostrare) implementa il protocollo NavgationTransitionable ?
- questa è la mia chiamata, nota il TRPushTransitionMethod.OMIN `navigationController?.tr_pushViewController(vc, method: TRPushTransitionMethod.OMIN(keyView: cell), statusBarStyle: TRStatusBarStyle.LightContent, completion: nil)`

**Comment by MattiaConfalonieri** [comment]
ho aggiunto var tr_transition: TRNavgationTransitionDelegate? al secondo controller e copiato paro paro la tua chiamata ma continuo a ricevere lo stesso errore.

**Comment by gali8** [comment]
..e che cavolo! Non so proprio che dirti... se mi viene in mente qualcosa ti scrivo su fb

**Comment by MattiaConfalonieri** [comment]
aspetta forse non ho capito cosa intendi per rendere il secondo vc NavgationTransitionable basta aggiungere  tr_transition: TRNavgationTransitionDelegate? ?

**Comment by MattiaConfalonieri** [comment]
Ok, ho riavviato xcode e ora funziona tutto... Jhonny è quasi magia.. grazie mille dell'aiuto...

**Comment by dianqk** [comment]
HiHi~  @gali8 @MattiaConfalonieri @danho322 @AlexEdunov ~  I add a [Example](https://github.com/DianQK/TransitionTreasury/tree/master/Example), hope you will love this.

You can see two example:
- Use `TransitionTreasury` & `TransitionAnimation`
- Only use `TransitionTreasury`
