### ISSUE TITLE
[Wrong]Running Project , BuildFailed, Where is the file to Open the Project? [报错]启动程序拨错,请问究竟该打开工程哪个文件?]

### ISSUE THREAD

**Issue by MISSAJJ** [DianQK/TransitionTreasury#16]
[Wrong]Running Project , BuildFailed, Where is the file to Open the Project?
[报错]启动程序拨错,请问究竟该打开工程哪个文件?]
#### 打开Demo.xcworkspace, 报错BuildFailed

:0: error: no such file or directory: '/Users/sl-office/Desktop/cici-document/TransitionTreasury-master/TransitionTreasury/TransitionAnimation/BlixtTransitionAnimation.swift'
:0: error: no such file or directory: '/Users/sl-office/Desktop/cici-document/TransitionTreasury-master/TransitionTreasury/TransitionAnimation/DefaultPushTransitionAnimation.swift'
:0: error: no such file or directory: '/Users/sl-office/Desktop/cici-document/TransitionTreasury-master/TransitionTreasury/TransitionAnimation/ElevateTransitionAnimation.swift'
:0: error: no such file or directory: '/Users/sl-office/Desktop/cici-document/TransitionTreasury-master/TransitionTreasury/TransitionAnimation/FadeTransitionAnimation.swift'
:0: error: no such file or directory: '/Users/sl-office/Desktop/cici-document/TransitionTreasury-master/TransitionTreasury/TransitionAnimation/IBanTangTransitionAnimation.swift'
:0: error: no such file or directory: '/Users/sl-office/Desktop/cici-document/TransitionTreasury-master/TransitionTreasury/TransitionAnimation/OMINTransitionAnimation.swift'
:0: error: no such file or directory: '/Users/sl-office/Desktop/cici-document/TransitionTreasury-master/TransitionTreasury/TransitionAnimation/PageTransitionAnimation.swift'
:0: error: no such file or directory: '/Users/sl-office/Desktop/cici-document/TransitionTreasury-master/TransitionTreasury/TransitionAnimation/PopTipTransitionAnimation.swift'
:0: error: no such file or directory: '/Users/sl-office/Desktop/cici-document/TransitionTreasury-master/TransitionTreasury/TransitionAnimation/ScanbotTransitionAnimation.swift'
:0: error: no such file or directory: '/Users/sl-office/Desktop/cici-document/TransitionTreasury-master/TransitionTreasury/TransitionAnimation/SlideTransitionAnimation.swift'
:0: error: no such file or directory: '/Users/sl-office/Desktop/cici-document/TransitionTreasury-master/TransitionTreasury/TransitionAnimation/TaaskyFlipTransitionAnimation.swift'
:0: error: no such file or directory: '/Users/sl-office/Desktop/cici-document/TransitionTreasury-master/TransitionTreasury/TransitionAnimation/TransitionAnimationHelper.swift'
:0: error: no such file or directory: '/Users/sl-office/Desktop/cici-document/TransitionTreasury-master/TransitionTreasury/TransitionAnimation/TRTransitionAnimations.swift'
:0: error: no such file or directory: '/Users/sl-office/Desktop/cici-document/TransitionTreasury-master/TransitionTreasury/TransitionAnimation/TwitterTransitionAnimation.swift'
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1
#### Open Example.xcworkspace 报错BuildFailed

PhaseScriptExecution Check\ Pods\ Manifest.lock /Users/sl-office/Library/Developer/Xcode/DerivedData/Example-diiaoutylokujcbeiztizdzqbfxl/Build/Intermediates/Example.build/Debug-iphonesimulator/Example.build/Script-BCB3429EE6F7935B99C4FC1B.sh
cd /Users/sl-office/Desktop/cici-document/TransitionTreasury-master/Example
/bin/sh -c /Users/sl-office/Library/Developer/Xcode/DerivedData/Example-diiaoutylokujcbeiztizdzqbfxl/Build/Intermediates/Example.build/Debug-iphonesimulator/Example.build/Script-BCB3429EE6F7935B99C4FC1B.sh

diff: /../Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

**Comment by dianqk** [comment]
@MISSAJJ  HiHi~ 抱歉，这个是我犯了个错误，Pod 路径设置错误，现已更新。

**Comment by MISSAJJ** [comment]
Thanx a lot~:)

**Comment by MISSAJJ** [comment]
still running wrong...

The file “TransitionAnimation.xcconfig” couldn’t be opened because there is no such file. (/Users/sl-office/Desktop/cici/TransitionTreasury-master/Demo/Pods/Target Support Files/TransitionAnimation/TransitionAnimation.xcconfig)
error: unable to read module map contents from 'Target Support Files/TransitionAnimation/TransitionAnimation.modulemap': Error Domain=NSCocoaErrorDomain Code=260 "The file “TransitionAnimation.modulemap” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/sl-office/Desktop/cici/TransitionTreasury-master/Demo/Pods/Target Support Files/TransitionAnimation/TransitionAnimation.modulemap, NSUnderlyingError=0x7fd6e6c834a0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
error: unable to read module map contents from 'Target Support Files/TransitionAnimation/TransitionAnimation.modulemap': Error Domain=NSCocoaErrorDomain Code=260 "The file “TransitionAnimation.modulemap” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/sl-office/Desktop/cici/TransitionTreasury-master/Demo/Pods/Target Support Files/TransitionAnimation/TransitionAnimation.modulemap, NSUnderlyingError=0x7fd6e6d05270 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}

**Comment by dianqk** [comment]
run `pod install` .

**Comment by MISSAJJ** [comment]
Thank u,I will try it this evening……

Warm Regards，

纯子(^_~)☆CiCi

**Comment by delphi-2015** [comment]
hi ~
the same question  running `Demo.xcworkspace` .
had run `pod install`
a pile of error
😂
<img width="218" alt="7061f305-4cb8-4143-9c16-623ccb1d6a5c" src="https://cloud.githubusercontent.com/assets/12149306/17641050/18bf227e-6143-11e6-8733-b074b43a53a3.png">

**Comment by dianqk** [comment]
Hi~ @delphi-2015  Please use Xcode 8 ，master has updated for Swift 2.3

**Comment by delphi-2015** [comment]
@DianQK got it, thank you! 😊
