### ISSUE TITLE
Xcode8 & swift 2.3 TransitionAnimation  class "ElevateTransitionAnimation" build Error

### ISSUE THREAD

**Issue by jimmyrogue** [DianQK/TransitionTreasury#31]
Xcode8 & swift 2.3 TransitionAnimation  class ElevateTransitionAnimation build Error

Line 88, 98 error
**Cannot assign value of type "ElevateTransitionAnimation" to type "CAAnimationDelegate?"**
Line 104 error 
**Method does not override any method from its superclass**
- TransitionAnimation, 3.0.4
- TransitionTreasury, 3.0.4

Help me please
Thank you

**Comment by dianqk** [comment]
Well ~ 
I will update as soon.

**Comment by jimmyrogue** [comment]
@DianQK  thanks

**Comment by dianqk** [comment]
I have push new tag [3.1.0](https://github.com/DianQK/TransitionTreasury/releases/tag/3.1.0) for Swift 2.3.
