### ISSUE TITLE
swift 3 is not supported!

### ISSUE THREAD

**Issue by baobao57** [DianQK/TransitionTreasury#38]
<img width="224" alt="2016-12-23 10 47 43" src="https://cloud.githubusercontent.com/assets/12264243/21446157/852046e2-c8fd-11e6-926a-0e984ae786da.png">

Excuse me, you recently have plan support swift 3?

**Comment by dianqk** [comment]
Hi
I have updated for Swift 3 just now.

You can see tag 4.0.0

**Comment by baobao57** [comment]
The current version of my cocoapods v1.1.1, but 'TransitionTreasury' i can only update to v3.1.0
<hr/>
<img width="570" alt="2016-12-26 8 35 05" src="https://cloud.githubusercontent.com/assets/12264243/21473452/632f7534-cb47-11e6-8207-1b305b33b574.png">
<hr/>
<img width="162" alt="2016-12-26 8 37 45" src="https://cloud.githubusercontent.com/assets/12264243/21473453/6974034c-cb47-11e6-85cf-627f14cc68f1.png">
<hr/>
<img width="311" alt="2016-12-26 8 43 12" src="https://cloud.githubusercontent.com/assets/12264243/21473451/632e0b0e-cb47-11e6-8eef-ef6975a2a427.png">

**Comment by dianqk** [comment]
```
$ pod 'Transitiontreasury', '~> 4.0'
```

**Comment by dianqk** [comment]
Please see this note:

```
as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default
```

**Comment by baobao57** [comment]
But my problem is that this causes:
`pod 'Transitiontreasury', '~> 4.0'`
when i use like this code：
`pod 'Transitiontreasury'`

I found only update to v3.1.0.

I believe that not only I happen this problem,your answer will not solve the problem.

**Comment by behrank** [comment]
need answer for this

**Comment by behrank** [comment]
i got the answer. clean your pod repo with
pod repo remove master
pod setup

then type   pod 'TransitionTreasury', '~> 4.0.0' to your pod file and pod install should be ok.

i ve done wtih it
