### ISSUE TITLE
Swift 3 -> Something wrong Here.

### ISSUE THREAD

**Issue by milanivarni** [DianQK/TransitionTreasury#39]
**Xcode 8.0 Swift 3.0**
![screen shot 2016-12-23 at 12 03 04 pm](https://cloud.githubusercontent.com/assets/22673922/21448385/087a49e8-c908-11e6-89aa-849805a619cf.png)

I integrated pods in my project as,

**pod 'TransitionTreasury', '~> 3.0.4'
pod 'TransitionAnimation'**

@DianQK  **Help me out from this.**

**Comment by dianqk** [comment]
change your version to 4.0.4:

```
pod 'Transitiontreasury', '~> 4.0'
```

**Comment by milanivarni** [comment]
Thank you brother.

**Comment by milanivarni** [comment]
**pod 'Transitiontreasury', '~> 4.0' Currently not available.**
![screen shot 2016-12-23 at 12 57 40 pm](https://cloud.githubusercontent.com/assets/22673922/21449076/7079f758-c90f-11e6-9b1e-9d22abb7d1ac.png)

**Comment by dianqk** [comment]
see note:

**as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.**

```shell
$ pod repo update
$ pod install
```

**Comment by baobao57** [comment]
I have the same problem waiting for solving. In fact and can't find higher than v3.1.0 version

**Comment by baobao57** [comment]
I solved the problem. I'm completely uninstalled `cocoapods`,After reinstalling `cocoapods`.Run the`pod install` again, the installation success!
<br/>
I think this is cocoapods problems caused by the old component.

**Comment by milanivarni** [comment]
@DianQK  Is there Objective-C Support?
